API Integration and Hide API Keys
lnabrigo18/rails-base-project pull request #15
Opened 2021-06-27 14:28 UTC by lnabrigo18

2021-06-27 15:01 UTC, Eunicegenel approved these changes

2021-06-28 00:52 UTC, analyn-cajocson requested changes
Kindly include the `Gemfile.lock` to this PR

2021-06-28 00:52 UTC, analyn-cajocson commented on app/models/broker_stock.rb
> +  validates :stock_id, presence: true
you don't have to validate the `foreign_keys`

2021-06-28 00:52 UTC, analyn-cajocson commented on app/models/broker_stock.rb
> +  validates :created_at, presence: true
Rails always gives `created_at` a value. You don't have to validate this attribute

2021-06-28 00:52 UTC, analyn-cajocson commented on app/models/buyer_stock.rb
> +  validates :created_at, presence: true
same comment as above

2021-06-28 00:52 UTC, analyn-cajocson commented on app/models/stock.rb
> +  validates :created_at, presence: true
same comment as above

2021-06-28 00:52 UTC, analyn-cajocson commented on app/models/transaction.rb
> +  validates :created_at, presence: true
same comment as above

2021-06-28 01:14 UTC, Eunicegenel approved these changes

2021-06-28 03:37 UTC, analyn-cajocson approved these changes

2021-06-28 03:38 UTC, merged